namespace LuckyStudentPicker
{
    [default_interface]
    runtimeclass NamelistTroubleshootingWindow : Microsoft.UI.Xaml.Window
    {
        NamelistTroubleshootingWindow();
        Int32 MyProperty;
    }
}
