namespace LuckyStudentPicker
{
    [default_interface]
    runtimeclass SeatArrangerErrorPrompt : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        SeatArrangerErrorPrompt();
        Int32 MyProperty;
    }
}